### PR TITLE
Update dependencies and tweak crossword css

### PR DESCRIPTION
**Pull request by pvspain**
Update dependencies  - using node 18.14
crossword-css-mods:
- Extract colors to variables
- Remove caret from focussed crossword cell
- Tweak colors for focussed cell and active clue

### CODE REVIEW

**Comment by dwmkerr** [comment]
This is great thank-you @pvspain !

**Comment by dwmkerr** [comment]
If you are planning to make more changes let me know, I'll add 'all contributors' to the project and a few other things hopefully to make it friendlier for contributors!

**Comment by pvspain** [comment]
Hi Dave,

Thanks!
Yes, I'd like to be a contributor please.
As part of familiarising myself with the code. I thought I would address
some of the ES lint issues - which will involve some simple refactoring.
Node LTS now supports most of the latest ES features according to node green
<https://node.green/>

Feature-wise, I noticed there is code to advance to the next cell as you
type, but that doesn't work(?). It's a feature I miss. Was that just a
stub, or did you have second thoughts?

Cheers, Paul

**Comment by pvspain** [comment]
Hi Dave,
Thanks for the add as a repo participant.
Do you want to have a look over these changes first?
Mostly addressing lint errors with some refactoring to accommodate ES changes.

**Comment by dwmkerr** [comment]
Thanks @pvspain I've merged this now, also just merged another branch that has some more developer friendly fixes:

- CircleCI is gone, replaced with GitHub actions
- 'Release Please' and 'All Contributors' enabled for the project (this will create 'release' pull requests when changes come in, and also allow tracking of contributors)

However, the highest priority issues are:

- Tests are failing
- Linting is failing
- Both test and lint steps are set to allow to fail on the build pipelines

I'd love any help on fixing up the first two issues for now, then maybe we can take a look at the 'TODO' section of the README, which has a quick and dirty list of open issues?

"All contributors" is really nice, I add a comment like the one below this and it creates a PR adding the contributor. Release please checks for changes to main, then looks at the commit history and then proposes updates to the changelog, version number and builds a release PR.

The changes I've made so far are in #14

**Comment by dwmkerr** [comment]
@all-contributors please add @pvspain for build, docs, code, tests

**Comment by dwmkerr** [comment]
@all-contributors please add @dwmkerr as a contributor for build, doc, code, test.
@all-contributors please add @pvspain for build, docs, code, tests

**Comment by dwmkerr** [comment]
@all-contributors please add @dwmkerr for build, doc, code, test.

@all-contributors please add @pvspain for build, docs, code, tests

**Pull request merged**
