### PR TITLE
Add support for multi-segment clue navigation to arrow keys

### PR DESCRIPTION
**Pull request by pvspain**
# nfc
- reformatting changes by **prettier**. Sorry - makes it hard to find logical changes! Are you using **prettier** @dwmkerr? If so we should add to the project with a config file for consistency.
# feature
- add support for multi-segment clue navigation to arrow keys - jump to next/prev segment. Add/reinstate `first`, `last` array helpers to `helpers.js`
# doc
- add documentation for multi-word answers and multi-segment clues.

### CODE REVIEW

**Comment by dwmkerr** [comment]
Looks good to me @pvspain - if we use prettier should we remove the eslint configuration?

**Comment by AncientSwordRage** [comment]
> Looks good to me @pvspain - if we use prettier should we remove the eslint configuration?

As much as it pains me to admit, having both is probably better, so long as you can configure them not to fight.

**Comment by dwmkerr** [comment]
No worries, I'll merge this now and fix up the eslint config!

**Comment by dwmkerr** [comment]
FYI @pvspain @AncientSwordRage I'm getting eslint and pretter to play nice, work in progress on #29 when that PR is green we should be good to go

**Pull request merged**
